name: voici-le-soleil
services:
  django:
    container_name: django
    build: 
      context: ..
      dockerfile: docker/dockerfiles/django/Dockerfile
    ports:
      - "8000:8000"
  nextjs:
    container_name: nextjs
    build:
      context: ..
      dockerfile: docker/dockerfiles/nextjs/Dockerfile.ci
    ports:
      - "3000:3000"