name: Deploy

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: rm frontend/cypress.config.ts && docker compose -f docker/ci.yml up -d --build

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Push Docker image
        run: |
          VERSION=v1
          echo "VERSION=$VERSION" >> $GITHUB_ENV

          docker tag voici-le-soleil-django ghcr.io/${{ github.repository }}/django:latest
          docker tag voici-le-soleil-nextjs ghcr.io/${{ github.repository }}/nextjs:latest
          docker push ghcr.io/${{ github.repository }}/django:latest
          docker push ghcr.io/${{ github.repository }}/nextjs:latest

      - name: Create .zip file
        env:
          VERSION: ${{ env.VERSION }}
        run: |
          cd aws
          zip -r deploy-${{ env.VERSION }}.zip docker-compose.yml Dockerrun.aws.json
          cp deploy-${{ env.VERSION }}.zip ../deploy-${{ env.VERSION }}.zip

      
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET }}
          application_name: ${{ secrets.APPLICATION_NAME }}
          environment_name: ${{ secrets.ENVIRONMENT_NAME }}
          version_label: ${{ env.VERSION }}
          region: eu-west-3
          deployment_package: deploy-${{ env.VERSION }}.zip