name: django

on:
  pull_request:

jobs:
  build:
    name: Django
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Start containers
        run: docker compose -f docker/development.yml up -d --build 

      - name: Run tests
        run: docker exec django python manage.py test